apiVersion: v1

kind: Service

metadata:

  annotations:

    service.beta.kubernetes.io/vultr-loadbalancer-protocol: "http"

  name: vultr-lb-http

spec:

  type: LoadBalancer

  selector:

    app: currency-rate-client

  ports:

    - port: 80
      targetPort: 8080
      name: "http"